### ISSUE TITLE
Add google Conversion Tracking Script

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/vt.at-drupal#111]
Below is the Google AdWords Conversion Tracking code for conversion action Course page.  To start tracking this conversion you need to copy and paste the code into the source of the page that you would like to track.

For tips see https://support.google.com/adwords/answer/6331314?&hl=en_GB.

```html
<!-- Google Code for Course page Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1026497607;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "pT7KCMnzxXUQx7i86QM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1026497607/?label=pT7KCMnzxXUQx7i86QM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
```

**Comment by Andreas-Schoenefeldt** [comment]
@ursulafeu will clarify, weather it is only for the polish website, or all websites. 
The main question is, do we need a seperate conversion tracking for every domain? If yes, It makes sense to do it based on a configuration in the admin panel.

**Comment by ursulafeu** [comment]
Hi Andreas, at the moment we only need it for Polish. 
But yes, we would need it for every domain. Russian might follow in a couple of weeks / months. 
For the German version there are no plans for online marketing.
So maybe it is more efficient for you to do it manually?

**Comment by Andreas-Schoenefeldt** [comment]
Ok, then I just put it to the code.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula - its now added for PL

**Comment by ursulafeu** [comment]
danke!
