### ISSUE TITLE
Remove Site Index of www.viszerale-therapie.co/vt/

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/vt.at-drupal#113]
Reported by @ursulafeu:

> hab ich grad zufällig entdeckt - die Seite www.viszerale-therapie.co/vt/ ist in Google indexiert und man kommt damit auf die alte Seite.
> Kannst Du da bitte die robots.txt dringend ändern oder eine Weiterleitung machen oder was sonst zu tun ist. 
> 
> Danke! :)
> Ursula

![pastedgraphic-1](https://user-images.githubusercontent.com/1157580/31122867-d5fb3750-a83d-11e7-9acb-eeb0387f63c9.png)

**Comment by Andreas-Schoenefeldt** [comment]
btw, ein richtig cooles ranking!

**Comment by ursulafeu** [comment]
das stimm! ist eh doof, wenn wir den zweiten Platz verschenken ... vielleicht fällt Dir ja was ein, wie wir den Platz trotzdem noch halten können? … wishfullfilling-Wunder-Andreas ?? ;)

**Comment by Andreas-Schoenefeldt** [comment]
Hm, guter Punkt - eventuell kommen wir irgendwie mit der Therapeutenliste rein? Also das wir die als eigene Webseite aufbauen?

**Comment by Andreas-Schoenefeldt** [comment]
Die Übernahme der viszerale-therapie.com scheint nicht richtig geklappt zu haben. Ich versuche Michael zu erreichen.

**Comment by Andreas-Schoenefeldt** [comment]
Ich glaube das hat sich jetzt erledigt, oder?

**Comment by ursulafeu** [comment]
ja - erfolgreich verjährt. ;)
schau mal, genau 1 Jahr her Dein letzter Kommentar.
