### ISSUE TITLE
Kursübersicht - Übersetzung der Legende

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/vt.at-drupal#117]
Lieber Andreas,
für die Legende in der Kursübersicht gibts noch keine Übersetzung-Tags. Kannst Du die Übersetzung bitte einfügen:

POLNISCH
1. availability (meaning bookable) dostępność
2. free places (or bookable) wolne mięjsca

RUSSISCH
1. availability (meaning bookable)- доступность 
2. free places (or bookable - свободные места

ENGLISCH
bitte nimm, was Du für besser hältst, Du bist geläufiger mit Englisch. danke!

**Comment by Andreas-Schoenefeldt** [comment]
Scheint erledigt zu sein - die Texte sind jetzt übersetzt :)
