### ISSUE TITLE
Therapeutenliste - kleine Änderungen

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/vt.at-drupal#124]
**Sonderausbildungen:**
1) "unerfüllter Kinderwunsch" ändern in "Kinderwunsch, Schwangerschaft und Geburt"
2) als Sonderausbildung ergänzen: Viszerales Taping

**Comment by ursulafeu** [comment]
Lieber Andreas, der Kurs Viszerales Taping findet in 1 Woche statt, danach sollte dieser als Eintrag in die Therapeutenliste möglich sein. Bitte die beiden Änderungen asap durchführen. Vielen lieben Dank!

**Comment by Andreas-Schoenefeldt** [comment]
Ach Herrje, das hab ich voll übersehen. Ich schau mal, wie das programmiert ist.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,

so klein war die benötigte Änderung leider nicht, aber das viszerale Taping sollte jetzt überall sichtbar sein. Wenn wir mal ein paar Tage Entwicklungsaufwand Zeit haben, sollten wir die Liste einfach so umbauen, das automatisch die Kurse aus dem Backend gezogen werden...

Ich habe auch etwas das Styling der Liste angepasst (um das herzbluten zu stoppen)

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
super, danke Andreas!
