### ISSUE TITLE
DSGVO - Kursanmeldung

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/vt.at-drupal#126]
**1) Titel entfernen:**
Dipl. PT

**2) Checkbox Fahrgemeinschaften ändern:**

Bildung von Fahrgemeinschaften: Ich stimme zu, dass meine Kontaktdaten (Name, Ort, Email, Tel.) den anderen KursteilnehmerInnen vor Kursbeginn übermittelt werden (zur Bildung von Fahrgemeinschaften). Meine Einwilligung zur Weitergabe meiner Daten an KursteilnehmerInnen gilt nur für diesen einen Kurs und verliert danach ihre Gültigkeit. 

**3) zusätzlich einfügen am Ende des Formulars:**

Datenschutzhinweis
Die im Formular angegebenen personenbezogenen Daten, die allein zum Zwecke der Durchführung des entstehenden Vertragsverhältnisses notwendig und erforderlich sind, werden auf Grundlage gesetzlicher Berechtigungen erhoben. Detaillierte Informationen zum Umgang mit Ihren Daten finden Sie in unserer Datenschutzerklärung.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,

das ist jetzt mit dem nächsten depoyment live, allerdings müssten die Texte auch für die anderen Sprachen nachgezogen werden. 

Das kannst du wie immer hier eintragen: https://viszerale-therapie.at/admin/config/regional/translate

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
Danke Andreas, ich bin grad bei den Übersetzungen dran. 
**Bitte noch was zu tun für Dich:**
--> Russisch: beide neuen Absätze entfernen (Fahrgemeinschaft und Datenschutz)

**Comment by Andreas-Schoenefeldt** [comment]
HI Ursula, bis jetzt hatten wir die anpassung des Forms nicht auf basis der Sprache, sondern auf Basis der Course location - ich hab den Datenschutz hinweis jetzt auch für russische Kurse raus genommen, passt das so?

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
ja Russisch unbedingt raus ;) danke!
Es ist jetzt aber noch online, dabei hab ich ganz ordentlich meinen Browser-Cache geleert:
https://visceral.com.ru/register/1?course-id=334

**Comment by Andreas-Schoenefeldt** [comment]
Auch für Russische Kurse? Da sollte es eigentlich weg sein - wie gesagt, die sprache selber hatte bis jetzt keinen Einfluss auf die darstellung der Kurse, sondern der eigentliche Ort der Kurse.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
genau, so war das ja. dann stimmt alles, vielen Dank! 
LG; Ursula
