### ISSUE TITLE
DSGVO - Therapeutenliste Verlinkungen

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/vt.at-drupal#130]
1) hier ist noch die alte Website Navigation drinnen - bitte weg, sodass man nicht mehr auf die alte Seite kommt. http://therapeuten.viszerale-therapie.at/datenschutzerklaerung.php

2) http://therapeuten.viszerale-therapie.at/therapeuten.php
Bitte das Impressum auf die neue Seite verlinken: http://viszerale-therapie.at/kontakt 

3) http://therapeuten.viszerale-therapie.at/therapeuten.php
Bitte in der Fußzeile ergänzen: Datenschutzhinweis

**Comment by Andreas-Schoenefeldt** [comment]
btw, die Therapeutenliste ist jetzt direkt unter https://therapeuten.viszerale-therapie.at/ zu erreichen.

cc @SVT-FlorindaCzeija

**Comment by ursulafeu** [comment]
👍
