### ISSUE TITLE
bug in der Kurs-Datumsauswahl

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/vt.at-drupal#137]
Lieber Andreas, es gibt einen Bug im Anmeldeformular. Leila hat mich drauf aufmerksam gemacht mit er Bitte das zu korrigieren: wählt man beispielsweise Moskaus, sieht man **alle** Termine, auch die der anderen Locations. Siehe Screenshot. 
danke! 

![kursbuchung-datumsauswhal](https://user-images.githubusercontent.com/23695891/47242631-9bd6f300-d3ef-11e8-8f96-1d4e5a179a51.png)

**Comment by Andreas-Schoenefeldt** [comment]
Spannend, ich schau mir das an.

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, ich habe eben mal geschaut und kann das nicht so ganz nachvolziehen. 

Also wenn ich zuerst den Ort selektiere, filtert er bei mir richtig. Wenn ich zuerst einen Kurs auswähle füllt er links den entsprechenden Ort aus, ABER es bleiben weiterhin alle Kurse verfügbar.

Ist das der Fehler? Das hatte ich damals bewusst so gemacht, weil ich es komisch fand, wenn man sichg verklickt und plötzlich alle Kurse weg sind. Wenn gewünscht, kann ich das aber gerne ändern, so dass auch eine direkte Kursauswahl den filter aktiviert.

Danke für eine kurze Bestätigung 
Andreas

**Comment by ursulafeu** [comment]
lass das mal so, die Russen hatten sich gewundert darüber. Aber die Usability macht natürlich Sinn so. Danke!
