### ISSUE TITLE
Add polish wating list

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/vt.at-drupal#138]

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,
das polinische Wartelisten icon ist jetzt da, willst du eventuell auch das booked-out übersetzen? Für Russisch könnten wir das auch einbauen, falls gewünscht.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
danke, ich hab dafür grad keine Übersetzung. Ich schließe das Ticket mal. :)
