### ISSUE TITLE
Fotos verzogen

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/vt.at-drupal#140]
Lieber Andreas,
wir haben eine neue Lehrerin dazu bekommen. Ihr Foto ist bei kleineren Bildschirmen in die Länge gezogen - kannst du das bitte richten: https://viszerale-therapie.at/ueber-uns/wir-stellen-uns-vor

Weiters ist das auch bei den Detailseiten der Fall: 
https://viszerale-therapie.at/ueber-uns/gudrun-hoellebrand
https://viszerale-therapie.at/ueber-uns/florinda-czeija 

danke! Alles Liebe, Ursula

**Comment by Andreas-Schoenefeldt** [comment]
Ich hab jetzt voll das coole modul gefunden, das er erlaubt content viel dynamischer einfach zusammen zu klicken. Ich schau mal, ob es sich lohnt das mit einzubauen.

Es wird dann “fast” wie wordpress für editoren :D

**Comment by Andreas-Schoenefeldt** [comment]
Done :) - Bilder gehen wieder.

Trick ist im quelltext den height parameter zu löschen. 

Liebe Grüße
Andreas
