### ISSUE TITLE
Kurstitel Anmeldebestätigungen - sollen englisch sein

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/vt.at-drupal#148]
Lieber Andreas, bei den Teilnahmbestästigungen sind die Kurstitel seit Neuestem nicht mehr auf Englisch, sondern in der jeweiligen Landessprache. Da die Teilnahmebestätigungen Englisch sind sollte auf der Kurstitel englisch ausgegeben werden. Das war auch immer so und jetzt nicht mehr?
Kannst Du das bitte wieder korrigieren, danke! Ich muss sonst alle Zertifikate einzeln nachbessern und umschreiben.
LG; Ursula

**Comment by Andreas-Schoenefeldt** [comment]
Hi @ursulafeu, um welchen Kurs geht es gerade?

**Comment by ursulafeu** [comment]
Zb der masterkurs der jetzt in Russland ist. Danke!

Von meinem iPhone gesendet

**Comment by Andreas-Schoenefeldt** [comment]
Ah ich seh schon - 338, gib mir bitte 15 minuten :)

**Comment by ursulafeu** [comment]
ja genau - alle Kurse die in Polen oder Russland stattfinden.

**Comment by Andreas-Schoenefeldt** [comment]
Alright, hab es umgestellt und deploye gleich noch die Textänderung

**Comment by ursulafeu** [comment]
Super, danke!!
