### ISSUE TITLE
fehlende Übersetzungsmöglichkeit für Dropdown-Feld

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/vt.at-drupal#161]
![grafik](https://user-images.githubusercontent.com/23695891/63647984-1fa4ee80-c729-11e9-9ebe-746dbd33b345.png)
Lieber Andreas, das "select an option" ist wohl neu - siehe Screenshot. Ich kann es leider nicht übersetzen. Kannst Du den Tag dafür setzen, danke!
LG, Ursula

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, ich kann das auf keinem meiner Browser sehen - welchen Broswer in welchem Betriebssystem verwendest du?

**Comment by ursulafeu** [comment]
bei mir ist es jetzt auch weg ... hat sich also offenbar erledigt. :) danke

**Comment by ursulafeu** [comment]
ich habs wieder gefunden - hier müsstest Du es sehen: https://viszerale-therapie.at/register/18

**Comment by Andreas-Schoenefeldt** [comment]
Check! Ich habs auch - mal schauen, wo das herkommt ;)

**Comment by Andreas-Schoenefeldt** [comment]
<img width="362" alt="Screenshot 2019-11-14 at 08 33 52" src="https://user-images.githubusercontent.com/1157580/68866140-95ca4900-06b9-11ea-8b14-e226834d52ec.png">

Scheint direkt aus dem choosen zu kommen

**Comment by Andreas-Schoenefeldt** [comment]
Das hab ich jetzt endlich gefunden :) - sollte erledigt sein, ohne dass du weiter etwas suchen musst.

**Comment by ursulafeu** [comment]
sehr gut, danke!
