### ISSUE TITLE
Tabellen-Layout anpassen für mobile

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/vt.at-drupal#27]
http://preview.czeija.com/wir-stellen-uns-vor

**Comment by Andreas-Schoenefeldt** [comment]
This is solved, no?

**Comment by ursulafeu** [comment]
I think this was about the course overview. This is not solved yet. It works but it is not user-friendly. I think people don't understand they can touch and scroll the list to the right.
I just looked into Google Analytics. The big junk of users is coming from mobile devices as you can see in the screenshot. 

Can you think of an easy-to-build solution for mobile usage?

![aufloesungen](https://user-images.githubusercontent.com/23695891/30706418-833c9b10-9ef8-11e7-9949-a585e8c10fcc.png)

**Comment by Andreas-Schoenefeldt** [comment]
Hm, maybe like this: 

**1. With a swipe hint above:**
![mobile-swipe](https://usfwebservices.files.wordpress.com/2013/06/table_swipe_screenshot.png)

**2. display change to collapse downwards per entry: (more complicated)**
![display-change](https://css-tricks.com/wp-content/uploads/2012/01/orig.jpg)
even niver:
![nice-flow](https://www.smashingmagazine.com/wp-content/uploads/2013/05/responsivetable03_mini.jpg)

**3. or something with scroll down / collapse, but this is even more complicated**
![collapse](https://css-tricks.com/wp-content/uploads/2012/12/footable-screenshot.jpg)

What do you think? The most simple solution would be the Nr. 1, but I think 2. or 3. is more elegant?

Best wishes
Andreas

**Comment by ursulafeu** [comment]
Thank you for the research. I'd say the second one is best. The enfold feature with plus and minus is not suitable in our case. Florinda also asked to show a key - how to interpret the different colors - because people sometimes don't understand their meaning straight away. Shall I go ahead and design the whole thing or do you start and I stir up your work afterwards with good suggestions? ;)

**Comment by Andreas-Schoenefeldt** [comment]
Would be great to have a layout for the legend, the table I will just try what I can do and then we can do a loop over that if needed.

**Comment by ursulafeu** [comment]
![kursubersicht-legende](https://user-images.githubusercontent.com/23695891/31021546-704a5c2e-a536-11e7-8945-e42bdc472c36.jpg)

**Comment by ursulafeu** [comment]
Lieber Andreas, bitte sag Bescheid, wenn das irgendwie doof ist in der Umsetzung / mobile usw...

**Comment by Andreas-Schoenefeldt** [comment]
Das passt soweit, ich schau mal was man mit der Tabelle in mobil sntellen kann :)

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, ich hab mal was imporvisiert: http://viszerale-therapie.at/kurse/kursuebersicht

Der Button unter jedem Kurseintrag im mobile habe ich eingebaut, weil es ja dort keinen Hover gibt - also sozusagen als "klick mich" Hilfe 😏 

Was denkst du?

**Comment by ursulafeu** [comment]
Die Idee mit dem Button bei mobile find ich sehr gut, genau so lassen! 👍 

Zwei optische Korrekturen hab ich noch bitte:

1. mobile
bitte die Kurstitel als h3 ausgeben, die gehen ein wenig unter sonst.

2. dektop
bitte das grau heller und die Schriften kleiner - im Layout war es doch so schön dezent ;)
Wenn sich das nicht so abbilden lässt bitte Schriften einfach kleiner und heller.

**Comment by Andreas-Schoenefeldt** [comment]
Ok, ich hab es nochmal geupdated (erst sichtbar nach dem nächsten Deployment)

**Comment by ursulafeu** [comment]
Die Kursübersicht ist jetzt grad total verschwunden. (desktop Ansicht)
Bitte guck mal, was da los ist. danke!

**Comment by Andreas-Schoenefeldt** [comment]
Hier ist ja was los… ;)

**Comment by Andreas-Schoenefeldt** [comment]
Es geht jetzt wieder :).

**Comment by ursulafeu** [comment]
Da gibts keine Translation tags für die Legende oberhalb der Kursübersicht.
Kannst Du das bitte noch hinterlegen oder die Übersetzungen direkt eingeben:
POLNISCH
1. availability (meaning bookable) dostępność
2. free places (or bookable) wolne mięjsca

**Comment by ursulafeu** [comment]
Florinda hatte auch noch eine gute Idee - die Button-Darstellung wäre auch gut für die Desktop-Version. Dann ist es nochmal selbsterklärender, was zu tun ist, um zu buchen. Ich hab das anbei mal aufgezeigt bei den ersten Reihen. Kannst Du das bitte umsetzen?

![kursubersicht-tabelle](https://user-images.githubusercontent.com/23695891/31324419-8e164884-acb2-11e7-861e-a75a4a1e5c85.jpg)

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, das ist jetzt da.

**Comment by ursulafeu** [comment]
super gelöst, danke! 
Ist noch ein Mouse-Over beim Button möglich?

**Comment by Andreas-Schoenefeldt** [comment]
Jep :)

**Comment by ursulafeu** [comment]
👍 danke!
