### ISSUE TITLE
Kurstitel auf Home - Umbrüche festlegen

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/vt.at-drupal#36]
das dürfen wir nicht vergessen ... da sind noch wilde Umbrüche:
![image](https://cloud.githubusercontent.com/assets/23695891/20701830/452e5d1c-b615-11e6-9b8a-3f1218ce243b.png)

**Comment by Andreas-Schoenefeldt** [comment]
Ok, ich hab es mit einem vernünftigen Umbruch gemacht und auch kleiner.

**Comment by ursulafeu** [comment]
Guten Morgen Du Fleißiger ... wir machen jetzt Schichtbetrieb an der Webseite! ;)
Danke fürs Umformtieren - leider geht sich das noch immer nicht für alle Kurse aus:
![image](https://cloud.githubusercontent.com/assets/23695891/20788615/d49486aa-b7b1-11e6-8cb1-cc89679e76ae.png)

Vorschlag: die blaue Box höher machen und den Zeilenabstand der Description verringern.
![image](https://cloud.githubusercontent.com/assets/23695891/20788655/f87538c6-b7b1-11e6-8cee-9dab8cae57a7.png)

Dann sollten wir insgesamt wieder so ungefähr auf der gleichen Höhe landen.

**Comment by ursulafeu** [comment]
**Umbrüche bei Home** passt jetzt super. 
**Anmeldeformular** - Wird das auch so angezeigt wenn man auf "Kurs buchen" klickt? Da sollte es auch mit Umbrüchen sein. ich konnte das grad nicht testen - da steht es gibt "Wartungsarbeiten" ;)
**Offen:**
1) kannst Du das mit der Größe noch anpassen? siehe oben ...
2) wie machen wir es im Menü und den Seitentiteln auf den Content-Seiten

**Comment by Andreas-Schoenefeldt** [comment]
| soll im Menü zum Zeilenumbruch werden.

**Comment by Andreas-Schoenefeldt** [comment]
font-size: 14px; line-height: 1.2, height: 4.6em

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, I adjusted the size.

**Comment by Andreas-Schoenefeldt** [comment]
btw, do we still need the feature to transform the | into a line break?

**Comment by ursulafeu** [comment]
We are talking about the side menu right?
As far as I know this is important to Florinda. So, yes please.

**Comment by ursulafeu** [comment]
das ist noch offen bitte. Florinda möchte gerne, dass auch im linken Menü die Umbrüche bestimmt werden können. Danke!

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, 
I made it now possible to add html tags to menu items, so you can use the <br/> tag at any point to create a line break.

Please don't overuse this ;)

Best wishes
Andreas

**Comment by ursulafeu** [comment]
Klappt - danke! :)
Ich hab jetzt ein <br/> eingefügt. Falls das nicht passt, sag bitte kurz Bescheid. danke!
